create table if not exists cliente(
codigo int not null primary key AUTO_INCREMENT,
nome varchar(50) not null unique
);

delete from cliente;

insert into cliente (nome) values('Alice');
insert into cliente (nome) values('Júlia');
insert into cliente (nome) values('Laura');
insert into cliente (nome) values('Manuela');
insert into cliente (nome) values('Beatriz');
insert into cliente (nome) values('Mariana');
insert into cliente (nome) values('Lívia');
insert into cliente (nome) values('Lorena');
insert into cliente (nome) values('Isadora');
insert into cliente (nome) values('Rafaela');
insert into cliente (nome) values('Sarah');
insert into cliente (nome) values('Ana Luiza');
insert into cliente (nome) values('Letícia');
insert into cliente (nome) values('Gabriela');
insert into cliente (nome) values('Melissa');
insert into cliente (nome) values('Clara');
insert into cliente (nome) values('Isis');
insert into cliente (nome) values('Ana Beatriz');
insert into cliente (nome) values('Larissa');
insert into cliente (nome) values('Alícia');
insert into cliente (nome) values('Valentina');
insert into cliente (nome) values('Helena');
insert into cliente (nome) values('Lara');
insert into cliente (nome) values('Julio');
insert into cliente (nome) values('Heloísa');
insert into cliente (nome) values('Alana');
insert into cliente (nome) values('Clarice');
insert into cliente (nome) values('Yasmin');
insert into cliente (nome) values('Aurora');
insert into cliente (nome) values('Elisa');
insert into cliente (nome) values('Bárbara');
insert into cliente (nome) values('Laís');
insert into cliente (nome) values('Luiza');
insert into cliente (nome) values('Emanuelle');
insert into cliente (nome) values('Mariane');
insert into cliente (nome) values('Sara');
insert into cliente (nome) values('Vitória');
insert into cliente (nome) values('Amanda');
insert into cliente (nome) values('Olívia');
insert into cliente (nome) values('Melinda');
insert into cliente (nome) values('Agnes');
insert into cliente (nome) values('Maísa');
insert into cliente (nome) values('Clarisse');
insert into cliente (nome) values('Estela');
insert into cliente (nome) values('Micaela');
insert into cliente (nome) values('Emanuela');
insert into cliente (nome) values('Anita');
insert into cliente (nome) values('Daniela');
insert into cliente (nome) values('Isa');
insert into cliente (nome) values('Sabrina');
insert into cliente (nome) values('Clarissa');
insert into cliente (nome) values('Angelina');
insert into cliente (nome) values('Flôr');
insert into cliente (nome) values('Arthur');
insert into cliente (nome) values('Bernardo');
insert into cliente (nome) values('Rafael');
insert into cliente (nome) values('Lorenzo');
insert into cliente (nome) values('Theo');
insert into cliente (nome) values('Felipe');
insert into cliente (nome) values('Henrique');
insert into cliente (nome) values('João Pedro');
insert into cliente (nome) values('Murilo');
insert into cliente (nome) values('Leonardo');
insert into cliente (nome) values('Isaac');
insert into cliente (nome) values('João');
insert into cliente (nome) values('Lucca');
insert into cliente (nome) values('Caio');
insert into cliente (nome) values('Bryan');
insert into cliente (nome) values('João Miguel');
insert into cliente (nome) values('Antônio');
insert into cliente (nome) values('Benício');
insert into cliente (nome) values('Thomas');
insert into cliente (nome) values('Miguel');
insert into cliente (nome) values('Gabriel');
insert into cliente (nome) values('Guilherme');
insert into cliente (nome) values('Pedro');
insert into cliente (nome) values('Nicolas');
insert into cliente (nome) values('Mateus');
insert into cliente (nome) values('David');
insert into cliente (nome) values('Yuri');
insert into cliente (nome) values('Joaquim');
insert into cliente (nome) values('Cristian');
insert into cliente (nome) values('Victor');
insert into cliente (nome) values('Evandro');
insert into cliente (nome) values('Calebe');
insert into cliente (nome) values('Emanuel');
insert into cliente (nome) values('Aarão');
insert into cliente (nome) values('Diogo');
insert into cliente (nome) values('Rodrigo');
insert into cliente (nome) values('Afonso');
insert into cliente (nome) values('Carlos');
insert into cliente (nome) values('Jonathan');
insert into cliente (nome) values('Leandro');
insert into cliente (nome) values('Marcelo');
insert into cliente (nome) values('Abel');
insert into cliente (nome) values('Jonas');
insert into cliente (nome) values('Renato');
insert into cliente (nome) values('Adriano');
insert into cliente (nome) values('Duarte');
insert into cliente (nome) values('Marcos');